### ISSUE TITLE
A question about the qr code challenge

### ISSUE THREAD

**Issue by P0IW** [thiagotmdev/QR-Code-Challenge#1]
Excuse me sir, i work on the same challenge 'qr code' and i have an issue in resizing the image, when i try to resize it the 'card' changes in the place of the 'image' . 
i hope you will help me ! thank you !
[index.md](https://github.com/thiagotmdev/QR-Code-Challenge/files/10716419/index.md)
![issue](https://user-images.githubusercontent.com/120593628/218321000-70761c95-95c0-4b40-832c-4c5079c75076.jpg)

**Comment by thiagotmdev** [comment]
> Excuse me sir, i work on the same challenge 'qr code' and i have an issue in resizing the image, when i try to resize it the 'card' changes in the place of the 'image' . 
> i hope you will help me ! thank you !
> [index.md](https://github.com/thiagotmdev/QR-Code-Challenge/files/10716419/index.md)
> ![issue](https://user-images.githubusercontent.com/120593628/218321000-70761c95-95c0-4b40-832c-4c5079c75076.jpg)
> 
> 

Put the class img inside of TAG img, that image Will work

**Comment by P0IW** [comment]
oh yeah it worked 😂, THANK YOU SO MUCH !

**Comment by P0IW** [comment]
**Excuse me,**
I'm just a total beginner and I'm just wondering how can i put or make the live site and for the screenshot in the Readme.md, do i make it the image tag like normal ? 
I'm really sorry 😅 I'm a beginner and this is my first time using gethub and my first challenge as well. 
I'm really sorry for bothering you !!! 🙏

**Comment by thiagotmdev** [comment]
@P0IW no problem, you Go on settings, of your repository and after in left side, you to click in option page, set o branch main and set option root and after click in save.
Waiting for some moments and appear the link of page

**Comment by P0IW** [comment]
Thank mate your are the best 🥲❤️

**Comment by thiagotmdev** [comment]
Thanks hehe 🎉🎉
